<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { getContentCategories, getDistricts, getPublicContents, getTags, type ContentCategory, type District, type PublicContent, type Tag } from '../api/contentApi'
import AppSelect from '@/components/common/input/AppSelect.vue'
import AppTextField from '@/components/common/input/AppTextField.vue'
import { getApiErrorMessage } from '@/features/auth/api/getApiErrorMessage'
import { useSwal } from '@/plugins/sweetalert'

const contents = ref<PublicContent[]>([]); const categories = ref<ContentCategory[]>([]); const districts = ref<District[]>([]); const tags = ref<Tag[]>([])
const search = ref(''); const categoryId = ref<string | null>(null); const districtId = ref<string | null>(null); const tagId = ref<string | null>(null); const loading = ref(true); const totalCount = ref(0); const swal = useSwal()
const activeFilterCount = computed(() => [search.value.trim(), categoryId.value, districtId.value, tagId.value].filter(Boolean).length)
function youtubeThumbnail(url?: string) { if (!url) return ''; try { const parsed = new URL(url); const id = parsed.hostname.includes('youtu.be') ? parsed.pathname.slice(1) : parsed.searchParams.get('v') ?? parsed.pathname.split('/').filter(Boolean).pop(); return id ? `https://i.ytimg.com/vi/${id}/hqdefault.jpg` : '' } catch { return '' } }
async function load() { loading.value = true; try { const result = await getPublicContents({ search: search.value || undefined, categoryId: categoryId.value || undefined, districtId: districtId.value || undefined, tagId: tagId.value || undefined, page: 1, pageSize: 100 }); contents.value = result.items; totalCount.value = result.totalCount } catch (error) { await swal.error('โหลดคอนเทนต์ไม่สำเร็จ', getApiErrorMessage(error, 'กรุณาลองใหม่อีกครั้ง')) } finally { loading.value = false } }
function clearFilters() { search.value = ''; categoryId.value = null; districtId.value = null; tagId.value = null; load() }
onMounted(async () => { try { [categories.value, districts.value, tags.value] = await Promise.all([getContentCategories(), getDistricts(), getTags()]) } catch { /* list remains available without filters */ } await load() })
</script>

<template>
  <div class="min-h-screen bg-slate-50 pb-16">
    <section class="relative overflow-hidden bg-gradient-to-br from-emerald-950 via-teal-900 to-slate-900 py-16 text-white sm:py-20"><div class="absolute -left-20 -top-24 h-80 w-80 rounded-full bg-emerald-400/15 blur-3xl" /><div class="absolute -right-16 -bottom-32 h-96 w-96 rounded-full bg-cyan-400/10 blur-3xl" /><div class="relative mx-auto max-w-7xl px-4 text-center sm:px-6"><span class="inline-flex items-center gap-2 rounded-full border border-emerald-300/30 bg-emerald-400/10 px-4 py-1.5 text-xs font-bold text-emerald-100"><i class="mdi mdi-compass-outline" /> Kanchanaburi Stories</span><h1 class="mt-4 text-3xl font-black tracking-tight sm:text-5xl">สำรวจเรื่องราว <span class="text-emerald-300">เมืองกาญจน์</span></h1><p class="mx-auto mt-4 max-w-2xl text-emerald-50/80">ค้นพบสถานที่น่าสนใจ กิจกรรม และเรื่องราวดี ๆ ในจังหวัดกาญจนบุรี</p></div></section>
    <main class="relative z-10 mx-auto -mt-7 max-w-7xl px-4 sm:px-6"><section class="rounded-3xl border border-emerald-100 bg-white p-5 shadow-xl shadow-emerald-950/5 sm:p-6"><div class="grid items-end gap-4 md:grid-cols-12"><div class="md:col-span-4"><label class="mb-1.5 block text-xs font-bold text-slate-500">ค้นหาคอนเทนต์</label><AppTextField v-model="search" placeholder="ชื่อสถานที่หรือเรื่องที่สนใจ" @keyup.enter="load" /></div><div class="md:col-span-3"><AppSelect v-model="categoryId" label="หมวดหมู่" :items="categories" item-title="categoryName" item-value="contentCategoryId" placeholder="ทุกหมวดหมู่" clearable /></div><div class="md:col-span-2"><AppSelect v-model="districtId" label="อำเภอ" :items="districts" item-title="districtName" item-value="districtId" placeholder="ทุกอำเภอ" clearable /></div><div class="md:col-span-2"><AppSelect v-model="tagId" label="แท็ก" :items="tags" item-title="tagName" item-value="tagId" placeholder="ทุกแท็ก" clearable /></div><div class="flex gap-2 md:col-span-1"><button class="flex h-11 flex-1 items-center justify-center rounded-xl bg-emerald-600 text-white shadow-lg shadow-emerald-600/20 hover:bg-emerald-700 disabled:opacity-60" :disabled="loading" title="ค้นหา" @click="load"><i class="mdi text-xl" :class="loading ? 'mdi-loading animate-spin' : 'mdi-magnify'" /></button><button v-if="activeFilterCount" class="flex h-11 w-11 items-center justify-center rounded-xl border border-slate-200 text-slate-600 hover:bg-slate-50" title="ล้างตัวกรอง" @click="clearFilters"><i class="mdi mdi-refresh" /></button></div></div><div v-if="activeFilterCount" class="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 text-sm"><span class="text-slate-500">กำลังใช้ตัวกรอง {{ activeFilterCount }} รายการ</span><button class="font-semibold text-emerald-700 hover:text-emerald-800" @click="clearFilters">ล้างทั้งหมด</button></div></section>
      <div class="my-7 flex items-center gap-3"><h2 class="text-xl font-bold text-slate-900">คอนเทนต์ล่าสุด</h2><span class="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-bold text-emerald-800">{{ loading ? '...' : totalCount }} รายการ</span></div>
      <section v-if="loading" class="grid gap-6 sm:grid-cols-2 lg:grid-cols-3"><div v-for="index in 6" :key="index" class="animate-pulse overflow-hidden rounded-3xl border border-slate-200 bg-white"><div class="h-48 bg-slate-200" /><div class="space-y-3 p-5"><div class="h-4 w-1/3 rounded bg-slate-200" /><div class="h-6 w-4/5 rounded bg-slate-200" /><div class="h-4 rounded bg-slate-200" /></div></div></section>
      <section v-else-if="contents.length" class="grid gap-6 sm:grid-cols-2 lg:grid-cols-3"><RouterLink v-for="content in contents" :key="content.contentId" :to="`/contents/${content.contentId}`" class="group overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:border-emerald-300 hover:shadow-xl hover:shadow-emerald-900/10"><div class="relative h-48 overflow-hidden bg-gradient-to-br from-emerald-700 via-teal-800 to-slate-900"><img v-if="youtubeThumbnail(content.youtubeUrl)" :src="youtubeThumbnail(content.youtubeUrl)" :alt="content.title" class="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div v-else class="flex h-full items-center justify-center text-emerald-200"><i class="mdi mdi-compass-rose text-6xl opacity-60" /></div><div class="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-transparent" /><span class="absolute left-4 top-4 rounded-full bg-white/15 px-3 py-1 text-xs font-bold text-white backdrop-blur">{{ content.contentCategoryName ?? 'คอนเทนต์' }}</span><span v-if="content.districtName" class="absolute bottom-3 left-4 inline-flex items-center gap-1 text-xs font-medium text-white"><i class="mdi mdi-map-marker" />{{ content.districtName }}</span></div><div class="p-5"><h3 class="line-clamp-2 text-xl font-bold text-slate-900 group-hover:text-emerald-700">{{ content.title }}</h3><p class="mt-2 line-clamp-2 min-h-10 text-sm leading-relaxed text-slate-600">{{ content.summary || 'ค้นพบเรื่องราวน่าสนใจจากกาญจนบุรี' }}</p><div class="mt-4 flex flex-wrap gap-1.5"><span v-for="tag in content.tags.slice(0, 3)" :key="tag.tagId" class="rounded-lg bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700">#{{ tag.tagName }}</span></div></div></RouterLink></section>
      <section v-else class="rounded-3xl border-2 border-dashed border-slate-200 bg-white px-6 py-16 text-center"><i class="mdi mdi-compass-off-outline text-5xl text-slate-300" /><h3 class="mt-4 text-xl font-bold text-slate-800">ไม่พบคอนเทนต์ที่ค้นหา</h3><p class="mt-2 text-slate-500">ลองเปลี่ยนคำค้นหา หรือล้างตัวกรองเพื่อดูรายการทั้งหมด</p><button class="mt-6 rounded-xl bg-emerald-600 px-5 py-3 font-semibold text-white hover:bg-emerald-700" @click="clearFilters">ล้างตัวกรอง</button></section>
    </main>
  </div>
</template>
