<script setup lang="ts">
import { onMounted, ref } from 'vue'
import http from '@/shared/api/http'
import { getApiErrorMessage } from '@/features/auth/api/getApiErrorMessage'
import { useSwal } from '@/plugins/sweetalert'
interface Order { orderId: string; orderNumber: string; totalAmount: number; orderStatus: string; paymentStatus: string; createdAt: string }
const orders = ref<Order[]>([]); const loading = ref(true); const swal = useSwal()
async function load() { try { const { data } = await http.get<Order[]>('/orders/shop/mine'); orders.value = data } catch (error) { await swal.error('โหลดออเดอร์ไม่สำเร็จ', getApiErrorMessage(error, 'กรุณาลองใหม่')) } finally { loading.value = false } }
async function updateStatus(order: Order, status: string) { try { await http.patch(`/orders/${order.orderId}/status`, { status }); order.orderStatus = status; await swal.success('อัปเดตสถานะแล้ว') } catch (error) { await swal.error('อัปเดตไม่สำเร็จ', getApiErrorMessage(error, 'กรุณาลองใหม่')) } }
onMounted(load)
</script>
<template><div class="mx-auto w-full max-w-6xl"><div v-if="loading" class="h-1 animate-pulse rounded bg-indigo-600" /><template v-else><div class="mb-8"><p class="font-semibold text-indigo-600">จัดการร้านค้า</p><h1 class="mt-1 text-3xl font-bold text-slate-900">ออเดอร์ลูกค้า</h1></div><div v-if="!orders.length" class="rounded-2xl border border-dashed border-slate-300 bg-white p-14 text-center text-slate-500">ยังไม่มีออเดอร์</div><div v-else class="space-y-4"><article v-for="order in orders" :key="order.orderId" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-wrap justify-between gap-3"><div><p class="font-bold text-slate-900">{{ order.orderNumber }}</p><p class="mt-1 text-sm text-slate-500">{{ new Date(order.createdAt).toLocaleString('th-TH') }}</p></div><p class="font-bold text-indigo-600">{{ Number(order.totalAmount).toLocaleString('th-TH') }} บาท</p></div><div class="mt-4 flex flex-wrap items-center gap-2"><span class="rounded-full bg-slate-100 px-3 py-1 text-sm">{{ order.orderStatus }}</span><span class="rounded-full px-3 py-1 text-sm" :class="order.paymentStatus === 'Paid' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'">ชำระเงิน: {{ order.paymentStatus }}</span><div class="ml-auto"><select class="rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:cursor-not-allowed disabled:bg-slate-100" :disabled="order.paymentStatus !== 'Paid'" :value="order.orderStatus" @change="updateStatus(order, ($event.target as HTMLSelectElement).value)"><option value="Confirmed">ยืนยันออเดอร์</option><option value="Shipped">จัดส่งแล้ว</option><option value="Completed">สำเร็จ</option><option value="Cancelled">ยกเลิก</option></select><p v-if="order.paymentStatus !== 'Paid'" class="mt-1 text-right text-xs text-amber-600">รอชำระเงินก่อน</p></div></div></article></div></template></div></template>
