<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import http from '@/shared/api/http'
import { getApiErrorMessage } from '@/features/auth/api/getApiErrorMessage'
import { useSwal } from '@/plugins/sweetalert'
interface Item { orderItemId: string; productName: string; quantity: number; unitPrice: number; totalPrice: number }
interface Order { orderNumber: string; subtotal: number; shippingFee: number; totalAmount: number; orderStatus: string; paymentStatus: string; createdAt: string; items: Item[] }
const route = useRoute(); const order = ref<Order | null>(null); const loading = ref(true); const swal = useSwal()
const totalItems = computed(() => order.value?.items.reduce((sum, item) => sum + item.quantity, 0) ?? 0)
onMounted(async () => { try { const { data } = await http.get<Order>(`/orders/${route.params.id}`); order.value = data } catch (error) { await swal.error('ไม่พบออเดอร์', getApiErrorMessage(error, 'กรุณาลองใหม่')) } finally { loading.value = false } })
</script>
<template><main class="mx-auto max-w-4xl px-4 py-10 sm:px-6"><div v-if="loading" class="h-1 animate-pulse rounded bg-indigo-600" /><template v-else-if="order"><RouterLink to="/orders" class="text-sm font-semibold text-indigo-600">← กลับคำสั่งซื้อ</RouterLink><section class="mt-5 rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><div class="flex flex-wrap justify-between gap-4"><div><p class="font-semibold text-indigo-600">คำสั่งซื้อ</p><h1 class="mt-1 text-2xl font-bold text-slate-900">{{ order.orderNumber }}</h1><p class="mt-1 text-sm text-slate-500">{{ new Date(order.createdAt).toLocaleString('th-TH') }}</p></div><div class="text-right"><span class="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold">{{ order.orderStatus }}</span><p class="mt-3 text-sm" :class="order.paymentStatus === 'Paid' ? 'text-emerald-600' : 'text-amber-600'">ชำระเงิน: {{ order.paymentStatus }}</p></div></div><div class="mt-7 border-t border-slate-100 pt-5"><h2 class="font-bold text-slate-900">สินค้า {{ totalItems }} ชิ้น</h2><div class="mt-4 space-y-3"><div v-for="item in order.items" :key="item.orderItemId" class="flex justify-between gap-4 rounded-xl bg-slate-50 p-4"><div><p class="font-semibold text-slate-900">{{ item.productName }}</p><p class="mt-1 text-sm text-slate-500">{{ Number(item.unitPrice).toLocaleString('th-TH') }} บาท × {{ item.quantity }}</p></div><p class="font-bold text-slate-900">{{ Number(item.totalPrice).toLocaleString('th-TH') }} บาท</p></div></div></div><div class="mt-7 space-y-3 border-t border-slate-100 pt-5 text-sm"><p class="flex justify-between"><span class="text-slate-500">ค่าสินค้า</span><span>{{ Number(order.subtotal).toLocaleString('th-TH') }} บาท</span></p><p class="flex justify-between"><span class="text-slate-500">ค่าจัดส่ง</span><span>{{ Number(order.shippingFee).toLocaleString('th-TH') }} บาท</span></p><p class="flex justify-between text-lg font-bold"><span>ยอดรวม</span><span class="text-indigo-600">{{ Number(order.totalAmount).toLocaleString('th-TH') }} บาท</span></p></div></section></template><div v-else class="py-16 text-center text-slate-500">ไม่พบออเดอร์</div></main></template>
