<script setup lang="ts">
import { onMounted, ref } from 'vue'
import http from '@/shared/api/http'
import { getApiErrorMessage } from '@/features/auth/api/getApiErrorMessage'
import { useSwal } from '@/plugins/sweetalert'
interface Order { orderId: string; orderNumber: string; totalAmount: number; orderStatus: string; paymentStatus: string; createdAt: string }
const orders = ref<Order[]>([]); const loading = ref(true); const swal = useSwal()
onMounted(async () => { try { const { data } = await http.get<Order[]>('/orders/mine'); orders.value = data } catch (error) { await swal.error('โหลดคำสั่งซื้อไม่สำเร็จ', getApiErrorMessage(error, 'กรุณาลองใหม่')) } finally { loading.value = false } })
</script>
<template><main class="mx-auto max-w-5xl px-4 py-10 sm:px-6"><div v-if="loading" class="h-1 animate-pulse rounded bg-indigo-600" /><template v-else><div class="mb-8"><p class="font-semibold text-indigo-600">การสั่งซื้อ</p><h1 class="mt-1 text-3xl font-bold text-slate-900">คำสั่งซื้อของฉัน</h1></div><div v-if="!orders.length" class="rounded-3xl border border-dashed border-slate-300 bg-white p-14 text-center text-slate-500">ยังไม่มีคำสั่งซื้อ</div><div v-else class="space-y-4"><article v-for="order in orders" :key="order.orderId" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="font-bold text-slate-900">{{ order.orderNumber }}</p><p class="mt-1 text-sm text-slate-500">{{ new Date(order.createdAt).toLocaleString('th-TH') }}</p></div><p class="text-lg font-bold text-indigo-600">{{ Number(order.totalAmount).toLocaleString('th-TH') }} บาท</p></div><div class="mt-4 flex flex-wrap items-center gap-2"><span class="rounded-full bg-amber-50 px-3 py-1 text-sm font-semibold text-amber-700">{{ order.orderStatus }}</span><span class="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold text-slate-600">ชำระเงิน: {{ order.paymentStatus }}</span><RouterLink :to="`/orders/${order.orderId}`" class="ml-auto rounded-lg border border-indigo-200 px-4 py-2 text-sm font-semibold text-indigo-600">ดูรายละเอียด</RouterLink><RouterLink v-if="order.paymentStatus !== 'Paid'" :to="`/orders/${order.orderId}/pay`" class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">ชำระเงิน</RouterLink></div></article></div></template></main></template>
